{% set name = "SDGym" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdgym-{{ version }}.tar.gz
  sha256: e53c8d54855b52e3b487bc55717cdd152e450704957c83a3a1e0aed9d0361f86

build:
  skip: true  # [py>=310]
  entry_points:
    - sdgym=sdgym.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pytest-runner >=2.11.1
    - pip
  run:
    - python
    - appdirs >=1.3,<2
    - boto3 >=1.15.0,<2
    - botocore >=1.18,<2
    - compress-pickle >=1.2.0,<3
    - humanfriendly >=8.2,<11
    - numpy >=1.18.0,<1.20.0  # [py<37]
    - pandas >=1.1.3,<2
    - pomegranate >=0.13.4,<0.14.2  # [py<37]
    - psutil >=5.7,<6
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.8.0,<2
    - tqdm >=4.15,<5
    - xlsxwriter >=1.2.8,<4
    - rdt >=0.6.1,<0.7
    - sdmetrics >=0.4.1,<0.5
    - sdv >=0.13.0

test:
  imports:
    - sdgym
  commands:
    - pip check
    - sdgym --help
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/SDGym
  summary: A framework to benchmark the performance of synthetic data generators for non-temporal tabular data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katxiao
